### ISSUE TITLE
Move to one col

### ISSUE THREAD

**Issue by nirik** [fedora-infra/tbs#4]
I think it would be nice to move to a single col for things, with: 

In progress 
Groomed
the rest

Right now 'the rest' is on the top left and is the first thing you see when you go to the page, but it's not the most important thing. We should put them in importance order, IMHO.

**Comment by 0xamrzaky** [comment]
from my point of view to give an easy way to explore the tickets and let people focus more, we should put each table at separated tab, so we'll get 4 tabs totally can user navigate between them instead of go to at end of page to get info
