### ISSUE TITLE
Consider dropping project field

### ISSUE THREAD

**Issue by nirik** [fedora-infra/tbs#6]
Consider moving the information from the project field into to ticket link... 
ie:

now:

Ticket link | Ticket info | Project | Assignee | Requester
-- | -- | -- | -- | --
6746 | Produce a slimmed-down compose whenever certain packages appear in an update | (pagure.io)/releng | Mohan Boddu | adamwill

proposed:

Ticket link | Ticket info | Asignee | Requestor
-- | -- | -- | -- 
pagure.io/releng/6746 | Produce a slimmed-down compose whenever certain packages appear in an update | Mohan Boddu | adamwill

Saves a col, and makes it easier to read IMHO, what do you all think?

**Comment by cverna** [comment]
+1 from me

**Comment by 0xamrzaky** [comment]
@cverna I think you should close this issue :)
